### ISSUE TITLE
SharpDistSensor is not in the Arduino Library Manager

### ISSUE THREAD

**Issue by ryantm** [DrGFreeman/SharpDistSensor#3]
Hello.

Thanks for making this library! We should totally get it added to the Arduino Library Manager. You do that by submitting an issue to the Arduino project on GitHub. You can look at how I did it here: https://github.com/arduino/Arduino/issues/5843

Ryan

**Comment by DrGFreeman** [comment]
@ryantm, Thanks for raising this issue! I will proceed as you suggest.

**Comment by DrGFreeman** [comment]
Issue #6135 raised in arduino/Arduino.
https://github.com/arduino/Arduino/issues/6135

**Comment by DrGFreeman** [comment]
Library has been added to the Arduino library manager. Closing issue.
