### ISSUE TITLE
Add an empty constructor to SharpDistSensor class to allow the creation of sensor arrays

### ISSUE THREAD

**Issue by Karosuo** [DrGFreeman/SharpDistSensor#8]
I don't know if adding this could bring a bug in terms of having objects initialized without pin number attached and window size, but it is really useful sometimes to have an array of sensors instead of statically adding variables per sensor.

I'm suggesting this, but let me know if it's not a good idea.

Thanks a lot for your work, really saved me tons of time.

**Comment by DrGFreeman** [comment]
Hello @Karosuo, first of all thanks for the feedback, I'm glad this library is useful to you!

Regarding your suggestion, I believe you can initialize an array of sensor objects without the need for an empty constructor this way:

```C++
SharpDistSensor sensorArray[] = {
  SharpDistSensor(A1, 1),  // First sensor using pin A1
  SharpDistSensor(A2, 1),  // Second sensor using pin A2
  // Add as many sensors as needed here...
};
```
Where you can pass the pin numbers to the constructors within the brackets.

Alternatively, this syntax should work as well:
```C++
SharpDistSensor sensorArray[2] = {{A1, 1}, {A2, 1}};
```

A complete basic sketch with an array of two sensors could look like this:

```C++
#include <SharpDistSensor.h>

// Number of sensors in array
const byte nbSensors = 2;

// Array of sensors
SharpDistSensor sensorArray[] = {
  SharpDistSensor(A1, 1), // First sensor using pin A1
  SharpDistSensor(A2, 1), // Second sensor using pin A2
};

// Array of unsigned integers to store distance values
uint16_t distArray[nbSensors];

void setup() {
  // Set some parameters for each sensor in array
  for (byte i = 0; i < nbSensors; i++) {
    sensorArray[i].setModel(SharpDistSensor::GP2Y0A710K0F_5V_DS);
  }
}

void loop() {
  // Read distance for each sensor in array into an array of distances
  for (byte i = 0; i < nbSensors; i++) {
    distArray[i] = sensorArray[i].getDist();
  }
}
```

Let me know if this meets your needs.

Note that the sketch above compiles OK but I could not test is on an actual Arduino since I have none available for now.

**Comment by Karosuo** [comment]
Thank you for the fast reply.
I'm currently using a similar option to that and appreciate all the code examples and explanation.
What I was thinking to do is something like:
`#define NUM_OF_SENSORS 4`
`SharpDistSensor sensor_instances_array[NUM_OF_SENSORS];`

Then initialize the array in the setup().
This way I can change the number of sensors just in one place.
In the other case, I would need to add the initialization part, and also the NUM_OF_SENSORS part.
Now this is for the case where I would need to add consecutive pin sensors, let's say A0, A1, A2, A3, which in my case it is.

But, maybe, that's not that usual because it is the second time I find this (a DHT11 library before)
In that ocation I added the empty constructor to the lib since I was the only one doing that prototype, but never asked if it really was a good idea.

So, I think that maybe I could do something like this:
```
SharpDistSensor sensorArray[] = {
  SharpDistSensor(A1, 1),  // First sensor using pin A1
  SharpDistSensor(A2, 1),  // Second sensor using pin A2
  // Add as many sensors as needed here...
};
#define NUM_OF_SENSORS sizeof(sensorArray)/sizeof(SharpDistSensor)
```
And I would have "change on one place" part without adding or changing the lib.

Just for the record, I can't test that last option right now, but as I don't know when I'm gonna be able to go and test it, I just added to the current answer.

**Comment by DrGFreeman** [comment]
I believe the use of array works well enough and I prefer not to modify the constructor and make it more confusing for entry-level users. I added a new example using arrays as above.

@Karosuo thanks for your input, hopefully this discussion and the new example will make it easier for others who want to use multiple sensors.

**Comment by Karosuo** [comment]
No problem!, thanks a lot for the follow-up and I'm sure that this will help someone, and congratulations for your commitment of adding examples and maintain your lib.
